#!/usr/bin/env python3
"""Bake original world-scale PBR maps for the Sol Action RPG terrain.

The source tile textures are original procedural textures generated by
`generate_textures.py`.  This baker composes them with authored biome masks,
curved routes, slope/height masks, and macro colour variation.  Runtime then
uses a single PBR terrain draw call instead of a flat vertex-colour plane.
"""
from pathlib import Path
import json
import math
import numpy as np
from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
TEX = ROOT / 'assets' / 'textures' / 'terrain'
OUT = TEX / 'world'
OUT.mkdir(parents=True, exist_ok=True)
SIZE = 1024
WORLD = 360.0
RADIUS = 172.0

ZONES = {
    'verdant': ((0.0, 0.0), 64.0, np.array([1.00, 1.00, 1.00])),
    'forest': ((-91.0, -24.0), 58.0, np.array([0.62, 0.82, 0.72])),
    'canyon': ((93.0, 14.0), 58.0, np.array([1.10, 0.91, 0.69])),
    'frost': ((-28.0, -103.0), 58.0, np.array([0.80, 1.02, 1.09])),
    'ember': ((25.0, 105.0), 59.0, np.array([0.70, 0.53, 0.49])),
    'astral': ((103.0, -94.0), 56.0, np.array([0.77, 0.68, 1.05])),
}


def load_layer(name, suffix):
    image = Image.open(TEX / f'{name}_{suffix}.webp').convert('RGB')
    tile = np.asarray(image, dtype=np.float32) / 255.0
    repeat = int(math.ceil(SIZE / tile.shape[0])) + 1
    tiled = np.tile(tile, (repeat, repeat, 1))[:SIZE, :SIZE]
    return tiled


def smoothstep(a, b, x):
    t = np.clip((x - a) / max(1e-6, b - a), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def segment_distance(px, pz, ax, az, bx, bz):
    abx, abz = bx - ax, bz - az
    denom = abx * abx + abz * abz + 1e-6
    t = np.clip(((px - ax) * abx + (pz - az) * abz) / denom, 0.0, 1.0)
    qx, qz = ax + t * abx, az + t * abz
    return np.sqrt((px - qx) ** 2 + (pz - qz) ** 2)


def save_rgb(arr, name, quality=90):
    arr = np.clip(arr * 255.0, 0, 255).astype(np.uint8)
    Image.fromarray(arr, 'RGB').save(OUT / name, 'WEBP', quality=quality, method=6)

# World coordinates. Image y runs north-to-south; JS PlaneGeometry UV maps z accordingly.
u = (np.arange(SIZE, dtype=np.float32) + .5) / SIZE
v = (np.arange(SIZE, dtype=np.float32) + .5) / SIZE
xx, zz = np.meshgrid((u - .5) * WORLD, (.5 - v) * WORLD)

# Stable macro terrain field; matching the runtime exact height is not required for the
# colour atlas, but the slope mask intentionally mirrors the same regional features.
macro = (
    np.sin(xx * .055 + np.cos(zz * .019) * 1.7) * .60
    + np.cos(zz * .047 - xx * .014) * .46
    + np.sin((xx + zz) * .023) * .38
    + np.cos(np.sqrt(xx * xx + zz * zz) * .07) * .20
)
detail = np.sin(xx * .29) * np.cos(zz * .27) * .16 + np.sin((xx - zz) * .17) * .12
height = macro * 2.2 + detail
# Regional relief.
cd = np.hypot(xx - 93.0, zz - 14.0)
height += (1.0 - smoothstep(34.0, 67.0, cd)) * (1.0 + np.abs(np.sin((xx + zz) * .075)) * 2.0)
fd = np.hypot(xx + 28.0, zz + 103.0)
height += (1.0 - smoothstep(30.0, 66.0, fd)) * 1.7
ed = np.hypot(xx - 25.0, zz - 105.0)
height += (1.0 - smoothstep(31.0, 66.0, ed)) * 1.2
height -= np.maximum(0.0, 1.0 - np.hypot(xx - 103.0, zz + 94.0) / 18.0) * 2.5
height *= 1.0 - (1.0 - smoothstep(10.0, 24.0, np.hypot(xx, zz))) * .92

gz, gx = np.gradient(height)
slope = np.sqrt(gx * gx + gz * gz)
slope_mask = smoothstep(.16, .68, slope)
high_mask = smoothstep(2.5, 5.2, height)

# Layer tiles with phase offsets so neighbouring material masks do not expose the same repetition.
layers = {}
for name in ('grass', 'dirt', 'sand', 'stone', 'path', 'cliff'):
    layers[name] = {
        suffix: np.roll(load_layer(name, suffix), (hash(name + suffix) % 197, hash(suffix + name) % 223), axis=(0, 1))
        for suffix in ('basecolor', 'normal', 'roughness', 'ao')
    }

# Soft biome weights.
weights = {}
for name, ((cx, cz), radius, _tint) in ZONES.items():
    d = np.hypot(xx - cx, zz - cz)
    weights[name] = np.clip(1.0 - d / (radius * 1.28), 0.0, 1.0) ** 2
weights['verdant'] += .11
wsum = sum(weights.values()) + 1e-6
for key in weights:
    weights[key] /= wsum

# Authored road network: camp to each regional landmark plus a loop around the camp.
road_distance = np.full_like(xx, 999.0)
for (cx, cz), _radius, _tint in [v for k, v in ZONES.items() if k != 'verdant']:
    # Two segments with an offset midpoint produce a hand-routed path instead of radial spokes.
    mx, mz = cx * .43 - cz * .055, cz * .43 + cx * .045
    road_distance = np.minimum(road_distance, segment_distance(xx, zz, 0.0, 3.5, mx, mz))
    road_distance = np.minimum(road_distance, segment_distance(xx, zz, mx, mz, cx * .86, cz * .86))
road_distance = np.minimum(road_distance, np.abs(np.hypot(xx, zz) - 12.7))
road = 1.0 - smoothstep(2.1, 4.7, road_distance)
road *= 1.0 - smoothstep(RADIUS - 10.0, RADIUS + 4.0, np.hypot(xx, zz))
plaza = 1.0 - smoothstep(11.6, 14.3, np.hypot(xx, zz))
path_mask = np.maximum(road, plaza)

# Material weights. Each biome gets a distinct physical character.
mat = {
    'grass': weights['verdant'] * .92 + weights['forest'] * .76 + weights['frost'] * .10,
    'dirt': weights['forest'] * .25 + weights['ember'] * .68 + weights['verdant'] * .10,
    'sand': weights['canyon'] * .78 + weights['frost'] * .16,
    'stone': weights['frost'] * .72 + weights['astral'] * .62 + weights['ember'] * .16,
    'cliff': weights['canyon'] * .30 + weights['ember'] * .46 + weights['astral'] * .32,
    'path': path_mask * 2.3,
}
mat['cliff'] += slope_mask * .95 + high_mask * .30
mat['grass'] *= 1.0 - slope_mask * .74
mat['sand'] *= 1.0 - slope_mask * .36
mat['path'] *= 1.0 - slope_mask * .52
matsum = sum(mat.values()) + 1e-6
for key in mat:
    mat[key] /= matsum

# Blend four maps consistently.
outputs = {}
for suffix in ('basecolor', 'normal', 'roughness', 'ao'):
    out = np.zeros((SIZE, SIZE, 3), dtype=np.float32)
    for key, mask in mat.items():
        out += layers[key][suffix] * mask[..., None]
    outputs[suffix] = out

# Biome tints and broad sun-bleached variation.
tint = np.zeros_like(outputs['basecolor'])
for name, (_center, _radius, zone_tint) in ZONES.items():
    tint += weights[name][..., None] * zone_tint[None, None, :]
noise = (np.sin(xx * .018 + zz * .027) + np.cos(xx * .011 - zz * .023)) * .025
outputs['basecolor'] *= tint * (1.0 + noise[..., None])
# Small irregular path shoulders and flower-soil flecks.
fleck = ((np.sin(xx * 2.13 + np.cos(zz * .31)) * np.sin(zz * 1.67) > .82) & (weights['verdant'] > .18)).astype(np.float32)
outputs['basecolor'] = outputs['basecolor'] * (1.0 - fleck[..., None] * .045) + np.array([.77, .68, .42]) * fleck[..., None] * .045

# Re-orient normals after tile blend and add macro relief normal.
normal = outputs['normal'] * 2.0 - 1.0
macro_n = np.dstack((-gx * 1.8, np.ones_like(gx), gz * 1.8))
macro_n /= np.linalg.norm(macro_n, axis=2, keepdims=True) + 1e-6
normal = normal * np.array([.45, .72, .45]) + macro_n * np.array([.55, .78, .55])
normal /= np.linalg.norm(normal, axis=2, keepdims=True) + 1e-6
outputs['normal'] = normal * .5 + .5

# Contact-friendly AO and believable roughness. Paths/stone are slightly less rough than grass.
outputs['ao'] *= (1.0 - np.clip(slope_mask * .08 + path_mask * .035, 0, .12))[..., None]
outputs['roughness'] = np.clip(outputs['roughness'] + (mat['grass'] * .05 - mat['stone'] * .06 - mat['path'] * .04)[..., None], .35, .98)

save_rgb(outputs['basecolor'], 'world_basecolor.webp', 92)
save_rgb(outputs['normal'], 'world_normal.webp', 91)
save_rgb(outputs['roughness'], 'world_roughness.webp', 88)
save_rgb(outputs['ao'], 'world_ao.webp', 88)
# Also persist a compact mask preview for documentation/debugging.
mask_preview = np.dstack((path_mask, slope_mask, weights['verdant']))
save_rgb(mask_preview, 'world_masks.webp', 86)

manifest_path = ROOT / 'assets' / 'manifests' / 'assets.json'
manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
for suffix, color_space in [('baseColor', 'srgb'), ('normal', 'linear'), ('roughness', 'linear'), ('ao', 'linear'), ('masks', 'linear')]:
    disk_suffix = {'baseColor':'basecolor'}.get(suffix, suffix)
    manifest['textures'][f'terrain.world.{suffix}'] = {
        'url': f'./assets/textures/terrain/world/world_{disk_suffix}.webp',
        'colorSpace': color_space,
        'anisotropy': 8,
        'repeat': [1, 1],
    }
manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
print('Baked', OUT)
